common:
  # dataset
  dataset_name: libriSpeech
  
  # audio
  audio_file_type: flac

  # annotation
  annotation_type: text

  # language
  country: us
  dialect: american
  language: en

  # speaker
  native: true
  age: adult

  # extra
  emotion: neutral
  comment: None
  vad_start: -1.0
  vad_end: -1.0


speaker_filepath: /home.local/aloradi/libriSpeech/train-clean-360/LibriSpeech/SPEAKERS.TXT
dataset_dir: /home.local/aloradi/libriSpeechs
annotation_format: .trans.txt
train_dir: /home.local/aloradi/libriSpeech/train-clean-360
test_dir: /home.local/aloradi/libriSpeech/test-clean
dev_dir: /home.local/aloradi/libriSpeech/dev-clean
